# a comment line
.PHONY: all clean run
CC=sjasmplus
all: main.o util.o
	$(CC) main.asm
run: all
	./run
clean:
	rm -f *.o
averyveryveryveryverylongtargetname: x
# padding line number 1 to push the file well past six hundred forty bytes total
# padding line number 2 to push the file well past six hundred forty bytes total
# padding line number 3 to push the file well past six hundred forty bytes total
# padding line number 4 to push the file well past six hundred forty bytes total
# padding line number 5 to push the file well past six hundred forty bytes total
# padding line number 6 to push the file well past six hundred forty bytes total
# padding line number 7 to push the file well past six hundred forty bytes total
# padding line number 8 to push the file well past six hundred forty bytes total
# padding line number 9 to push the file well past six hundred forty bytes total
# padding line number 10 to push the file well past six hundred forty bytes total
# padding line number 11 to push the file well past six hundred forty bytes total
# padding line number 12 to push the file well past six hundred forty bytes total
# padding line number 13 to push the file well past six hundred forty bytes total
# padding line number 14 to push the file well past six hundred forty bytes total
# padding line number 15 to push the file well past six hundred forty bytes total
# padding line number 16 to push the file well past six hundred forty bytes total
# padding line number 17 to push the file well past six hundred forty bytes total
# padding line number 18 to push the file well past six hundred forty bytes total
# padding line number 19 to push the file well past six hundred forty bytes total
# padding line number 20 to push the file well past six hundred forty bytes total
# padding line number 21 to push the file well past six hundred forty bytes total
# padding line number 22 to push the file well past six hundred forty bytes total
# padding line number 23 to push the file well past six hundred forty bytes total
# padding line number 24 to push the file well past six hundred forty bytes total
# padding line number 25 to push the file well past six hundred forty bytes total
# padding line number 26 to push the file well past six hundred forty bytes total
# padding line number 27 to push the file well past six hundred forty bytes total
# padding line number 28 to push the file well past six hundred forty bytes total
# padding line number 29 to push the file well past six hundred forty bytes total
# padding line number 30 to push the file well past six hundred forty bytes total
# padding line number 31 to push the file well past six hundred forty bytes total
# padding line number 32 to push the file well past six hundred forty bytes total
# padding line number 33 to push the file well past six hundred forty bytes total
# padding line number 34 to push the file well past six hundred forty bytes total
# padding line number 35 to push the file well past six hundred forty bytes total
# padding line number 36 to push the file well past six hundred forty bytes total
# padding line number 37 to push the file well past six hundred forty bytes total
# padding line number 38 to push the file well past six hundred forty bytes total
# padding line number 39 to push the file well past six hundred forty bytes total
# padding line number 40 to push the file well past six hundred forty bytes total
