Dss.ChDisk       EQU #01
Dss.CurDisk      EQU #02

Dss.Create       EQU #0A

Dss.Open         EQU #11
Dss.Close        EQU #12
Dss.Read         EQU #13
Dss.Write        EQU #14
Dss.Move_FP      EQU #15

Dss.ChDir        EQU #1D
Dss.CurDir       EQU #1E

Dss.WaitKey      EQU #30

Dss.SetVMod      EQU #50
Dss.GetVMod      EQU #51
Dss.Cursor       EQU #53
Dss.Locate       EQU #52
Dss.Clear        EQU #56

Dss.GetMem       EQU #3D
Dss.FreeMem      EQU #3E

Dss.Exec         EQU #40
Dss.Exit         EQU #41
Dss.Wait         EQU #42

Dss.AppInfo      EQU #47

Dss.PChars       EQU #5C
