SLOT0           EQU #82
SLOT1           EQU #A2
SLOT2           EQU #C2
SLOT3           EQU #E2

PORT_Y          EQU #89
RGMOD           EQU #C9
BorderColor     EQU #FE

SYS_PORT.ON     EQU #7C
SYS_PORT.OFF    EQU #3C

Z84.CTC.Ch_0        EQU #10
Z84.CTC.Ch_1        EQU #11
Z84.CTC.Ch_2        EQU #12
Z84.CTC.Ch_3        EQU #13

Z84.SIO.Ch_A.Data   EQU #18
Z84.SIO.Ch_A.Ctrl   EQU #19
Z84.SIO.Ch_B.Data   EQU #1A
Z84.SIO.Ch_B.Ctrl   EQU #1B

Z84.PIO.Port_A.Data     EQU #1C
Z84.PIO.Port_A.Command  EQU #1D
Z84.PIO.Port_B.Data     EQU #1E
Z84.PIO.Port_B.Command  EQU #1F

ToBIOS          EQU #08
ToDSS           EQU #10
ToBIOS_18       EQU #30
